### ISSUE TITLE
Not compatible with Ember-CLI 3.2.x

### ISSUE THREAD

**Issue by pichfl** [willrax/ember-luxon#87]
```
Circular dependency: tmp/rollup-cache_path-aCxGLew4.tmp/build/impl/locale.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/settings.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/impl/locale.js
Circular dependency: tmp/rollup-cache_path-aCxGLew4.tmp/build/datetime.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/duration.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/impl/locale.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/datetime.js
Circular dependency: tmp/rollup-cache_path-aCxGLew4.tmp/build/datetime.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/interval.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/datetime.js
Circular dependency: tmp/rollup-cache_path-aCxGLew4.tmp/build/datetime.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/info.js -> tmp/rollup-cache_path-aCxGLew4.tmp/build/datetime.js

Build Error (broccoli-persistent-filter:Babel > [Babel: PROJECTNAME]) in luxon.js

luxon.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null

Stack Trace and Error Report: /var/folders/sk/f8z9r_gd3qx0ycfccdxbfd7c0000gn/T/error.dump.406a591d1c334e86c29e015452028671.log
```

I'll try to fix this in our fork and will try to provide a PR.

**Comment by buschtoens** [comment]
```
luxon.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null
```

is caused by https://github.com/moment/luxon/commit/2b65af4a58b91039934628961b468ef803f939e6, because of https://github.com/babel/ember-cli-babel/issues/171#issuecomment-318916469

Pinning to luxon to `1.3.0` (the last version before that commit) fixes the error.

However the build later then dies with

```
Error: ENOENT: no such file or directory, open '/Users/janbuschtoens/clark/application/client/tmp/source_map_concat-input_base_path-UjcfuCrb.tmp/vendor/luxon.js'
    at Object.openSync (fs.js:434:3)
    at Object.readFileSync (fs.js:339:35)
    at SourceMap.addFile (/Users/janbuschtoens/clark/application/node_modules/fast-sourcemap-concat/lib/source-map.js:77:33)
    at headerFiles.forEach.file (/Users/janbuschtoens/clark/application/node_modules/broccoli-concat/concat.js:196:18)
    at Array.forEach (<anonymous>)
    at Concat.concat.end.concat (/Users/janbuschtoens/clark/application/node_modules/broccoli-concat/concat.js:194:26)
    at /Users/janbuschtoens/clark/application/node_modules/fast-sourcemap-concat/lib/source-map.js:431:14
    at new Promise (<anonymous>)
    at SourceMap.end (/Users/janbuschtoens/clark/application/node_modules/fast-sourcemap-concat/lib/source-map.js:418:12)
    at Concat._doLegacyBuild (/Users/janbuschtoens/clark/application/node_modules/broccoli-concat/concat.js:179:24)
```
